name: NPM Publish

on:
  release:
    types:
      - published

jobs:
  npm-publish:
    permissions:
      contents: read
      id-token: write
    uses: hemilabs/.github/.github/workflows/npm-publish.yml@2900f1ef5a775d5d1f96ae012f5ad5d6e98cd6ec # v1.3.1
    with:
      package-manager: pnpm
    secrets: inherit
